# Example configuration using Google Gemini

llm:
  provider: google_gemini
  google_gemini_api_key: "YOUR_GEMINI_API_KEY" # Store securely, e.g., via GEMINI_API_KEY env var
  google_gemini_model_name: "gemini-2.0-flash" # Or another available model like gemini-pro

# Add other top-level configurations like 'messaging' and 'agent' as needed
# Example:
# messaging:
#   driver: mqtt
#   broker_address: localhost
#   port: 1883
#   topics:
#     log: agent/log
#     # ... other topics

# agent:
#  log_level: INFO 