site_name: Argentic
site_description: Documentation for the Argentic project.

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: indigo
      accent: indigo
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: indigo
      accent: indigo

plugins:
  - search
  - same-dir
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - import os
            # Add the absolute path to src, which is one level up from docs/
            - src_path = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "src")) if "__file__" in locals() else os.path.abspath("../src")
            - if src_path not in sys.path:
            -   sys.path.insert(0, src_path)
            - 'sys.stderr.write("MKDOCSTRINGS_PYTHON_SYS_PATH_FROM_DOCS_YML: " + str(sys.path) + "\n")'
          options:
            show_root_heading: true
            show_source: true
  - macros:
      include_dir: '..'

nav:
  - Home: index.md
  - API Reference:
    - Messager: api/messager.md
    - Message Structures: api/messages.md
    - Messaging Drivers: api/drivers.md
  # Add other pages and sections here
  # Example:
  # - User Guide:
  #   - 'Getting Started': 'user-guide/getting-started.md'
  #   - 'Configuration': 'user-guide/configuration.md'
  # - API:
  #   - 'Core API': 'api/core.md'

# If you want to include your root README.md as the main page,
# you'll copy it to docs/index.md. We'll do this in the GitHub Action.
# Or, for local builds, you can do it manually or with a script.

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      css_class: highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - admonition
  - toc:
      permalink: true

# You can also add markdown extensions if needed
# markdown_extensions:
#   - pymdownx.highlight:
#       anchor_linenums: true
#   - pymdownx.inlinehilite
#   - pymdownx.snippets
#   - pymdownx.superfences

site_dir: ../_site
docs_dir: . 