name: Deploy Documentation to GitHub Pages

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read  # To checkout the repository
  pages: write    # To deploy to GitHub Pages
  id-token: write # To enable OIDC token authentication for GitHub Pages

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
    - name: Install documentation dependencies with uv
      run: |
        uv pip install --system -e .[docs]
    - name: Prepare docs source
      run: |
        set -x # Print each command before executing
        mkdir -p docs/assets
        cp assets/logo.jpg docs/assets/logo.jpg # For theme and for the final path in docs/index.md
        
        cp README.md docs/index.md # Copy root README to docs/index.md
        # sed command removed as README.md now has the correct final path for docs/index.md
        # sed -i 's|!\[Argentic Logo\](./docs/assets/logo.jpg){: .styled-logo }|!\[Argentic Logo\](./assets/logo.jpg){: .styled-logo }|g' docs/index.md

        # Find all README.md files, excluding .git, .github, docs, and virtual environment directories
        find . -path ./docs -prune -o -path ./.git -prune -o -path ./.github -prune -o -path ./.venv -prune -o -path ./venv -prune -o -name "README.md" -type f | while read -r file; do
          # Create a relative path for the destination in docs/
          # Example: ./src/moduleA/README.md -> docs/src/moduleA/index.md
          dest_dir="docs/$(dirname "${file#./}")"
          mkdir -p "$dest_dir"
          cp "$file" "$dest_dir/index.md"
        done
        # Find all other .md files (excluding README.md as they are handled above, and excluding specified directories)
        # and copy them, maintaining their original names and directory structure within docs/
        find . -path ./docs -prune -o -path ./.git -prune -o -path ./.github -prune -o -path ./.venv -prune -o -path ./venv -prune -o -name "*.md" -not -name "README.md" -type f | while read -r file; do
          dest_path="docs/$(dirname "${file#./}")/$(basename "$file")"
          mkdir -p "$(dirname "$dest_path")"
          cp "$file" "$dest_path" # Changed back from cp -r, as these are files
        done
        # Add commands here to copy other READMEs or markdown files into the docs/ directory
        # For example: 
        # mkdir -p docs/module1
        # cp src/module1/README.md docs/module1/index.md 
    - name: Build MkDocs documentation
      run: |
        mkdocs build --config-file docs/mkdocs.yml --site-dir _site
    - name: Setup Pages
      uses: actions/configure-pages@v5
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: '_site' # Upload the _site directory
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4 
